// Terms & Acknowledgements — shown from the login/signup screen.
// ------------------------------------------------------------------
// TERMS_VERSION is recorded alongside the caregiver's consent timestamp so a
// future revision can re-prompt. Keep the copy in plain, humane language —
// the reader is often an exhausted family member, not a lawyer.

import React from 'react';
import { X } from 'lucide-react';

export const TERMS_VERSION = '2026-07-16';

interface TermsModalProps {
  onClose: () => void;
}

const H: React.FC<{ children: React.ReactNode }> = ({ children }) => (
  <h3 className="text-sm font-extrabold text-[#2C2C2A] mt-5 mb-1.5">{children}</h3>
);

export const TermsModal: React.FC<TermsModalProps> = ({ onClose }) => (
  <div
    className="fixed inset-0 z-[60] bg-black/50 flex items-center justify-center p-4"
    onClick={onClose}
  >
    <div
      className="bg-white rounded-3xl border border-[#E3DFC2] shadow-2xl w-full max-w-lg max-h-[85vh] flex flex-col"
      onClick={(e) => e.stopPropagation()}
      role="dialog"
      aria-modal="true"
      aria-label="Terms and Acknowledgements"
    >
      <div className="flex items-center justify-between px-6 py-4 border-b border-[#EFECDD]">
        <h2 className="text-lg font-bold text-[#2C2C2A]">Terms &amp; Acknowledgements</h2>
        <button
          type="button"
          onClick={onClose}
          className="p-2 rounded-xl text-[#7E7D76] hover:bg-[#F4F1EA] transition-all"
          aria-label="Close"
        >
          <X className="w-5 h-5" />
        </button>
      </div>

      <div className="px-6 py-4 overflow-y-auto text-[13px] leading-relaxed text-[#5E5D57]">
        <p className="text-xs text-[#8A8981]">Version {TERMS_VERSION}</p>

        <H>1. What Yadira is — and is not</H>
        <p>
          Yadira is an AI companion for people living with dementia, paired with tools for their
          caregivers. It is designed for comfort, connection, and caregiving support.{' '}
          <b>Yadira is not a medical device.</b> It does not diagnose, treat, cure, or prevent any
          condition, and nothing it says is medical advice. Decisions about medication, diagnosis,
          or treatment belong with a qualified clinician. <b>In an emergency, contact emergency
          services immediately</b> — never Yadira.
        </p>

        <H>2. AI limitations</H>
        <p>
          Yadira's conversations are generated by artificial intelligence. AI can be wrong,
          inconsistent, or confusing despite our safeguards. You are responsible for supervising
          how it is used with the person in your care, and for discontinuing use if it causes
          distress.
        </p>

        <H>3. Vivid Mode and represented personas</H>
        <p>
          Vivid Mode lets the companion speak in the voice and name of a real person — often
          someone who has passed away — as a validation-therapy comfort measure. By enabling it,
          you affirm that: you have the moral and (where applicable) legal standing to represent
          that person; you are doing so for the wellbeing of the person in your care; and you
          remain responsible for monitoring how they respond. Yadira never claims these
          conversations are real, and this feature must never be used to deceive anyone for
          financial or legal purposes.
        </p>

        <H>4. Caregiver responsibility</H>
        <p>
          Account holders must be 18 or older. You are the responsible adult in this arrangement:
          Yadira supplements human care — it is <b>never</b> a substitute for supervision, human
          contact, or professional care. The patient-facing companion is provided free for
          families; you remain responsible for how your household or facility uses it.
        </p>

        <H>5. Privacy and data</H>
        <p>
          Conversations, memories, care logs, and check-ins are stored to make Yadira work
          (via Google Firebase) and are processed by the AI and voice services that power the
          product (including Google Gemini, OpenRouter, and Inworld) and by Stripe for payments.
          We use this data to provide and improve the service for your family — not to sell it.
          Please don't enter information you are not authorized to share. Yadira is not intended
          to be a system of record for regulated medical data.
        </p>

        <H>6. Payments</H>
        <p>
          The patient-facing companion is free. Caregiver Pro is a $5/week subscription billed
          through Stripe; you can cancel any time via the billing portal and access continues to
          the end of the paid period. Care-facility partnerships are billed per-unit under
          separate agreement.
        </p>

        <H>7. Acceptable use</H>
        <p>
          Don't use Yadira to harm, harass, defraud, or impersonate anyone for deceptive
          purposes, or to violate any law. We may suspend accounts that put a patient or other
          people at risk.
        </p>

        <H>8. No warranty; limitation of liability</H>
        <p>
          Yadira is provided "as is," without warranties of any kind. To the fullest extent the
          law allows, we are not liable for indirect, incidental, or consequential damages
          arising from use of the service.
        </p>

        <H>9. Changes</H>
        <p>
          We may update these terms as the product evolves. If we make material changes, you'll
          be asked to review and accept the new version.
        </p>

        <H>10. Contact</H>
        <p>
          Questions? Reach us at <b>partnerships@yadira.app</b>.
        </p>
      </div>

      <div className="px-6 py-4 border-t border-[#EFECDD]">
        <button
          type="button"
          onClick={onClose}
          className="w-full py-3 bg-[#3A5D45] text-white font-bold rounded-xl hover:bg-[#2B4633] transition-all"
        >
          Close
        </button>
      </div>
    </div>
  </div>
);

export default TermsModal;
